data:
  path: "/Users/tim-bhp/PycharmProjects/link_predictions_supply_chains/Link-Prediction-Supply-Chains/data/02_intermediate"

device: 'cpu' # change to 'cuda' for GPU
stream_wandb: True

# Config for running data engineering from scratch...
de:
  from_scratch: False  # Recreate everything from scratch
  triplets_from_scratch: False  # Recreate all triplets
  load_graph: True  # Loading the already saved DGL Graph into Memory
  capability_product_weight_cut: 200
  cg_weight_cut: 30
  graph_save_path: 'data/02_intermediate/'

plotting:
  path: 'data/04_results/'

modelling:
  num_node_features: 15
  num_hidden_graph_layers: 16
  num_negative_samples: 3
  num_classes: 2
  batch_size: 64 # Mini batch size for the graph
  num_epochs: 8000
  evaluate_every: 3 # How many epochs should pass before an evaluation run?
  test_p: 0.3
  num_workers: 0
  loss: "binary_cross_entropy" # Or could also be 'margin'
  log_freq: 20

# Graph Neural Network training parameters (not mutually exclusive with above)
net:
  lr: 1e-3
  optimiser: "Adam"
  l2_regularisation: 5e-4 # Regularisation term for the GNN weights
  loss: "binary_cross_entropy" # Or could also be 'margin'
#  inference_edge: ('company', 'buys_from', 'company')

testing:
  batch_size: 2048
  log_freq: 10

embedding_net:
  lr: 1e-4
  optimiser: "Adam"
  l2_regularisation: 5e-4
  loss: 'margin'
